### ISSUE TITLE
Can't log in.

### ISSUE THREAD

**Issue by Bestiedamo1** [ThScEo/AutoForge#31]
Hello, I've tried logging in the past few days and I now keep getting an error every time I try.
I even brought the monthly thing for extra features recently but now this doesn't work at all, the error I keep getting is this:
Error parsing message : Sorry, an internal error occurred. Please try again later {'title': 'Exception', 'message': 'Sorry, an internal error occurred. Please try again later', '__class__': 'Error'}
Connection failed.
Error when login. Check your credentials or sid and user key

I did find that before also, the program would just randomly stop working whilst it was running.

**Comment by onicniepytaj** [comment]
Same for me. I'm new to this project although I'm inputting the correct data. I've got the very same error.

**Comment by ThScEo** [comment]
Hi,

This issue should be fixed, keep me informed, thanks.

**Comment by onicniepytaj** [comment]
Thanks. Seems like I can login however it's crashing quite often. Most of the times window will just close but sometimes not and then I can see the below:
![image](https://user-images.githubusercontent.com/56124935/225913570-5c5d727e-c85f-4e8f-bf32-bfecc607b7a5.png)

**Comment by ThScEo** [comment]
Hi,

I will share a new release soon to fix this issue

**Comment by reitut** [comment]
Still have this message:

Connection failed.
Error when login : local variable 'response' referenced before assignment

**Comment by ThScEo** [comment]
Hi, a new version of the bot is available, please upgrade, and keep me informed :)

**Comment by onicniepytaj** [comment]
Great stuff. It works for a longer time now. It fell over after like 2.5h which is a progression. Previously it was crashing much faster.

This is how it stopped:
![image](https://user-images.githubusercontent.com/56124935/232313734-201ca72f-e517-43b5-8118-eb297dfabfa9.png)

**Comment by onicniepytaj** [comment]
On 0.4.4:
![image](https://user-images.githubusercontent.com/56124935/232323576-fd231dd0-de14-40b8-b65d-9715cc7aa9de.png)

**Comment by onicniepytaj** [comment]
![image](https://user-images.githubusercontent.com/56124935/232324517-ef73d2f8-428e-4334-b73f-9369eb606176.png)

**Comment by ThScEo** [comment]
> ![image](https://user-images.githubusercontent.com/56124935/232324517-ef73d2f8-428e-4334-b73f-9369eb606176.png)

Please tell me if the issue is still happening. Thank you.

**Comment by reitut** [comment]
> Still have this message:
> 
> Connection failed. Error when login : local variable 'response' referenced before assignment

Now the message is: Error when login. Check your credentials or sid and user key. Checked. Maybe I'm forgeting something?

**Comment by reitut** [comment]
> Still have this message:
> 
> Connection failed. Error when login : local variable 'response' referenced before assignment

Now the message is: "Connection failed : Desculpe, sua sessão expirou. Por favor faça login novamente.
Error when login. Check your credentials or sid and user key"
Checked.

**Comment by ThScEo** [comment]
Please Try with the latest release [0.4.7](https://github.com/ThScEo/AutoForge/releases/tag/v0.4.7) , and tell me if there is an error about metadata. Thank you

**Comment by reitut** [comment]
Thank you for your request for metadata about the data/resource in question. I am happy to provide this information to you, but I would like to know if there are any specific requirements or guidelines you have for formatting or providing the metadata.
Is there any additional information or clarification you need me to provide to ensure the metadata is accurate and useful for your needs?

Thank you for your time and support.

Best regards, Reitut
![log](https://user-images.githubusercontent.com/130266669/235799949-3fd49b4a-eaba-483c-a18e-1554ca0579e3.png)

**Comment by ThScEo** [comment]
Please send me an email at thsceo@proton.me, including all logins details : SID, user key and URL. 
Maybe you are not filling theses informations correctly.
